### ISSUE TITLE
PDFoundry has been deprecated

### ISSUE THREAD

**Issue by NeurohrByteS** [farling42/fvtt-cypher-addons-compendiums#5]
> PDFoundry has been deprecated as Foundry VTT now includes builtin PDF support, and there are only a few cases where PDFoundry's extra features exceed Foundry's. It may return one day to provide the missing features, but will require enough work to do so that it is currently not viable without a more complete re-write.
So long, and thanks for all the fish!

https://github.com/Djphoenix719/PDFoundry

**Comment by farling42** [comment]
I saw that.
I haven't found the syntax to open a PDF at a specific page though :-(

**Comment by NeurohrByteS** [comment]
I was also looking for it. It seems like currently there is no way.
I'm playing around with within the next days, if I find anything I'll update this issue.

**Comment by NeurohrByteS** [comment]
Thank you for requesting the necessary feature in Foundry core.
https://github.com/foundryvtt/foundryvtt/issues/8151

**Comment by farling42** [comment]
I've made a new module pdf-pager which will support #page=xxx inside standard @UUID links to PDF documents.

See https://github.com/farling42/fvtt-pdf-pager

**Comment by NeurohrByteS** [comment]
I will test it asap, on Saturday the latest (this week my calendar is well filled).

**Comment by NeurohrByteS** [comment]
Rebuilt a couple of pages. Some text renderers in custom character sheets don't work with pdf pager (no button/link generated), but I'm quite sure that the PDFoundry links didn't work either. Everything based on Journal pages works perfectly!

Thank you very much!

**Comment by farling42** [comment]
I'm not sure what you're referring to, I'm no expert on PDFs.

I did find a PDF for Call of Cthulhu which has some automatically calculated fields in it, which caused problems with PDF Pager which I've just fixed in 0.13.0

**Comment by farling42** [comment]
IF you have an example PDF that you can share, I can investigate.

**Comment by NeurohrByteS** [comment]
Sorry for being confusing, everything is alright.
I promised to test, it was unfortunately a week later than promised.


+ Everything you implemented worked great.
+ I use the PDFs mainly to prevent copy-pasting complex rules, especially if a character's ability requires rules from multiple pages.
+ Journal pages and the preview of the built-in formatted text editor always work with [fvtt-pdf-pager](https://github.com/farling42/fvtt-pdf-pager)
+ However some character sheets use the plaintext content of the wysiwyg-editor and of course those lose the PDF-link.
  + I'm not certain if the old PDFoundry managed to override that behaviour, but I guess it didn't
  + So it would be an issue I would have to raise to the module providing the character sheet

**Comment by farling42** [comment]
A soft dependency has been mentioned in the readme to my "PDF Pager" module which will perform all the functions required to support this compendium.
